version: "3.8"

services:
  app:
    image: node:14
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=login_db
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ["sh", "-c", "npm install && node server.js"]

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
